Feat/challenge 03 loops conditionals
HuevoPlatino/JavaScript-Foundations-Challenge1 pull request #5
Opened 2023-10-31 18:24 UTC by HuevoPlatino

2023-11-05 16:45 UTC, tictools requested changes
`node_modules` folder should never be pushed to remote repository.

In order to remove it, follow these steps:
* remove `node_modules` folder in your remote repository (branch `feat/challenge_03_loops-conditionals`)
* move to your local repo (same branch) and execute `git pull`
* fix requested changes and push them.

2023-11-05 16:45 UTC, tictools commented on .prettierignore
This file is empty.

⚠️ FIX: add `node_modules`

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/CHALLENGE.md
`README.md` should only be defined at root level (in fact, it is already there)

⚠️ FIX: remove `README.md` from this folder and leave only the root one.

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
> +if (animal === "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +if (number % 2 === 0) {
⚠️ FIX: Change the variable to test it works for different cases. Print result.

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let i = 10; i <= 40; i += 2) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the odd/even ones

You should take in account what variables are storing in order to name them properly. Is variable `i` referring to any index in this case?

⚠️ FIX: rename properly `for` variables in both cases

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +for (let i = 1; i <= 10; i++) {
⚠️ FIX: rename properly `for` variables in both cases

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +console.log("---Exercise 2---");
This is the output of your script...
```
---Exercise 2---
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Half way there!
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

⚠️ FIX: rename properly `for` variable

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_00.js
> +while (loggedIn === false) {
This is the output of your script...
```
Incorrect login credentials
Successfully logged in!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +while (num <= 40) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the odd/even ones

2023-11-05 16:45 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +while (i <= 100) {
This is the output of your script...
```
---Exercise 3---
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Half way there!
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
All, done!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

You should take in account what variables are storing in order to name them properly. Is variable `i` referring to any index in this case?

⚠️ FIX: rename properly `i` variable

2023-11-10 14:38 UTC, tictools requested changes

2023-11-10 14:38 UTC, tictools commented on challenge_02_variable_operators/index (1).html
FIX: remvoe `(1)` from  file name

2023-11-10 14:38 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
Your are duplicating code and this is not a good idea... You should encapsulate this logic
```js
 if (animal === "cat") {
   console.log("Meow!");
 } else if (animal === "dog") {
   console.log("Woof!");
 } else {
   console.log("Must be an alien");
 }
```
inside a function which returns the expected string.

Then call it and log its returned value.

FIX: encapsulate logic

2023-11-10 14:38 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
Your are duplicating code and this is not a good idea... You should encapsulate this logic
```js
if (number % 2 === 0) {
  console.log("Even");
} else {
  console.log("Odd");
}
```
inside a function which returns the expected string.

Then call it and log its returned value.

FIX: encapsulate logic

2023-11-10 15:21 UTC, tictools requested changes

2023-11-10 15:21 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
You must iterate over all numbers between 10 and 40 and log even or odd ones, depending on the case. 
Do not increase iterations by 2.

FIX: iterate over all numbers.

2023-11-10 15:21 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +  let random = Math.floor(Math.random() * 10) + 1;
FIX: stablish a new line between blocks
```suggestion
  let random = Math.floor(Math.random() * 10) + 1;
  
  if(...){
  //..
  }
```

2023-11-10 15:21 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +  if (index === 50) {
FIX: add new line between blocks

2023-11-12 13:16 UTC, tictools requested changes

2023-11-12 13:16 UTC, tictools commented on .github/workflow/pipeline.yaml
You've got `.github/workflow/pipeline.yaml`

You should have `.github/workflows/pipeline.yaml` // worflows, not workflow

This check will never be executed

FIX: typo.

2023-11-12 13:16 UTC, tictools commented on .gitingnore
`.gitignore`, not`.gitingnore`

FIX: typo

2023-11-12 20:28 UTC, tictools approved these changes

2023-11-12 21:17 UTC, GALLEGOOOO approved these changes

2023-11-13 08:42 UTC, merged